/**
 * Códigos de permissão do tenant, derivados de `prisma/seed.ts`.
 *
 * O seed é a fonte de verdade; `permission-codes.spec.ts` falha se os dois
 * divergirem, para que nenhuma tool nova dependa de um código inventado.
 */

export const PERMISSION_CODES = [
  'ai.use',
  'audit.view',
  'auth.login',
  'auth.logout',
  'auth.refresh',
  'automations.create',
  'automations.delete',
  'automations.edit',
  'automations.view',
  'billing.manage',
  'billing.view',
  'calendar.create',
  'calendar.delete',
  'calendar.edit',
  'calendar.view',
  'contacts.create',
  'contacts.delete',
  'contacts.edit',
  'contacts.view',
  'daily_routine.complete',
  'daily_routine.manage',
  'daily_routine.view',
  'dashboard.view',
  'email.admin',
  'email.view',
  'notifications.manage',
  'notifications.view',
  'projects.archive',
  'projects.create',
  'projects.delete',
  'projects.edit',
  'projects.manage_members',
  'projects.manage_views',
  'projects.view',
  'reports.export',
  'reports.view',
  'roles.assign',
  'roles.create',
  'roles.edit',
  'roles.view',
  'settings.edit',
  'settings.view',
  'tasks.assign',
  'tasks.attachments_manage',
  'tasks.change_priority',
  'tasks.change_status',
  'tasks.checklist_manage',
  'tasks.comment',
  'tasks.create',
  'tasks.delete',
  'tasks.edit',
  'tasks.move',
  'tasks.view',
  'teams.create',
  'teams.delete',
  'teams.edit',
  'teams.manage_members',
  'teams.view',
  'users.create',
  'users.disable',
  'users.edit',
  'users.view',
] as const;

export type PermissionCode = (typeof PERMISSION_CODES)[number];
